services:
  palworld-dedicated:
    build: "."
    restart: unless-stopped
    ports:
      - "8211:8211/udp"
    volumes:
      - data:/home/steam/palworld
      - ./PalWorldSettings.ini:/home/steam/palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini:ro
    environment:
      - SERVER_PLAYERS=32
      - SERVER_PORT=8211
      - USER_ID
      - GROUP_ID
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "32g"
        reservations:
          memory: "16g"

volumes:
  data:

