services:
  palworld-dedicated:
    build: "."
    tty: true
    restart: unless-stopped
    ports:
      - "8211:8211/udp"
    volumes:
      - data:/palworld
      - ./PalWorldSettings.ini:/home/docker/PalServer/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini:ro
    environment:
      - SERVER_PLAYERS=32
      - SERVER_PORT=8211
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "32g"
        reservations:
          memory: "16g"

volumes:
  data:

